baseurl = ""
title = "Orfeas Antoniou"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = false

PygmentsCodeFences = true
pygmentscodefencesguesssyntax = true
PygmentsStyle = "monokai"

googleAnalytics = "UA-156939402-1"

enableRobotsTXT = true

[params]
    author = "Orfeas Antoniou"
    info = "A Software Engineer with experience in Project Management. Based in London, UK."
    description = "Orfeas Antoniou personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/profile.png"
    #gravatar = "orfeas@orfeasa.com"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidefooter = false    
    footercontent = ""

    hidecredits = true
    hidecopyright = true

    # Enable the Right To Left mode
    rtl = false

    math = false
    custom_css = ["css/style.css"]

    # Specify light/dark color scheme
    # Supported values: "auto", "dark", "light"
    colorscheme = "light"

    # Enable Twemoji
    enableTwemoji = true


# Social links
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-2x"
    # icon order
    weight = 1
    url = "https://github.com/orfeasa/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/orfeasa/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"