baseurl = ""
title = "Orfeas Antoniou"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

canonifyurls = false

PygmentsCodeFences = true
pygmentscodefencesguesssyntax = true
PygmentsStyle = "monokai"

googleAnalytics = "G-PQTFXJSMPH"

enableRobotsTXT = true

[params]
author = "Orfeas Antoniou"
info = "Engineering Manager at Thought Machine (London), leading a team building and operating cloud-native core banking services."
description = "Engineering Manager at Thought Machine in London, leading a team responsible for core banking services within Vault Core."
keywords = "engineering management,backend engineering,go,grpc,microservices,distributed systems,reliability,operational excellence,fintech,core banking,delivery management,stakeholder management,technical leadership"
avatarurl = "images/profile.png"
socialimage = "img/social.png"
#gravatar = "orfeas@orfeasa.com"

hidefooter = true
footercontent = ""

hidecredits = true
hidecopyright = true

# Enable the Right To Left mode
rtl = false

math = false
customCSS = ["css/style.css"]

# Specify light/dark color scheme
# Supported values: "auto", "dark", "light"
colorScheme = "auto"

# Enable Twemoji
enableTwemoji = false


# Social links
[[params.social]]
name = "GitHub"
icon = "fab fa-github fa-2x"
# icon order
weight = 1
url = "https://github.com/orfeasa/"
[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/orfeasa/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "Projects"
#     weight = 2
#     url = "/projects/"
[[menu.main]]
name = "About"
weight = 3
url = "/about/"
